services:
  px4-sitl:
    build:
      context: ../3d-path-planner
      dockerfile: docker/Dockerfile
    image: px4-planner:latest

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]

    volumes:
      - ../3d-path-planner:/root/3d-path-planner:rw

    ports: !override
      - "5902:5901"
      - "6080:6080"
      - "14550:14550/udp"
      - "18570:18570/udp"
